### ISSUE TITLE
指正：最早的容器技术应该为FreeBSD jail

### ISSUE THREAD

**Issue by Alex6357** [FDUCSLG/COMP101#5]
具体可见红帽这篇文章：[什么是 Linux 容器？](https://www.redhat.com/zh/topics/containers/whats-a-linux-container)

**Comment by w568w** [comment]
我是该篇的作者，谢谢指正。

我做了一些[搜索](https://www.aquasec.com/blog/a-brief-history-of-containers-from-1970s-chroot-to-docker-2016/)。更严格地说，容器技术能追溯到 1979 年在 Unix V7 的前身 `chroot`。1982 年，`chroot` 被添加到 BSD 4.4 中，并在 2000 年最终演进为 FreeBSD Jails。
